sudo: required
services:
 - docker

before_install:
 - docker build -t ankur111/docker-react -f Dockerfile.dev .

script:
 - docker run ankur111/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-west-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-west-1-281128570780"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
